# IdeaBase GraphQL Schema
# 版本: 20260705224113

# 自定义标量类型
scalar Json
scalar Cursor
scalar DateTime

# 排序方向枚举，包含NULL值处理
enum SortDirection {
  ASC
  DESC
  ASC_NULLS_FIRST
  DESC_NULLS_FIRST
  ASC_NULLS_LAST
  DESC_NULLS_LAST
}

# 空值条件枚举
enum IsInput {
  NULL
  NOT_NULL
}

# 百科历史
type AppHistory {
  # 作者
  authorId: Int
  # 变更说明
  changeNote: String
  # 创建时间
  createdAt: DateTime
  # 创建人
  createdBy: Int
  # 逻辑删除
  deletedAt: DateTime
  # 删除人
  deletedBy: Int
  # 最后编辑
  editorId: Int
  # 主键
  id: ID!
  # 词条ID
  lineageId: Int
  # 版本快照
  payload: Json
  # 发布时间
  publishAt: DateTime
  # 备注
  remark: Json
  # 状态
  state: Int
  # 更新时间
  updatedAt: DateTime
  # 更新人
  updatedBy: Int
  # 版本号
  version: Int
  # 权重
  weight: Int
}

# 百科词条
type AppLineage {
  # 别名
  alias: Json
  # 封面
  cover: String
  # 创建时间
  createdAt: DateTime
  # 创建人
  createdBy: Int
  # 逻辑删除
  deletedAt: DateTime
  # 删除人
  deletedBy: Int
  # 难度
  difficulty: Int
  # 草稿内容
  draft: Json
  # 生态环境分类
  environment: Json
  # 图标
  icon: String
  # 主键
  id: ID!
  # 学名标题
  latin: String
  # 内容载体
  payload: Json
  # 父级
  pid: Int
  # 发布时间
  publishAt: DateTime
  # 人类关系分类
  relationship: Json
  # 备注
  remark: Json
  # 状态
  state: Int
  # 中文标题
  title: String
  # 更新时间
  updatedAt: DateTime
  # 更新人
  updatedBy: Int
  # 版本
  version: Int
  # 权重
  weight: Int
}

type Comment {
  # 全部祖先（递归）
  ancestors(where: CommentWhereInput, sort: [CommentSortInput!], limit: Int, offset: Int, depth: Int): [Comment]!
  # 子Comment列表
  children(where: CommentWhereInput, sort: [CommentSortInput!], limit: Int, offset: Int): [Comment]!
  content: String!
  createdAt: DateTime!
  # 全部后代（递归）
  descendants(where: CommentWhereInput, sort: [CommentSortInput!], limit: Int, offset: Int, depth: Int): [Comment]!
  id: ID!
  # 父Comment对象
  parent: Comment
  parentId: ID
  # 关联的Post
  post: Post!
  postId: ID!
  # 关联的User
  user: User!
  userId: ID!
}

# 文件对象记录
type OssFile {
  # 创建时间
  createdAt: DateTime
  # 创建人
  createdBy: Int
  # 逻辑删除
  deletedAt: DateTime
  # 删除人
  deletedBy: Int
  # 原始文件名
  filename: String
  # 文件哈希
  hash: String
  # 存储ID
  hostId: Int
  # 主键
  id: ID!
  # 上传IP
  ip: String
  # 文件类型
  mimeType: String
  # 对象Key
  objectKey: String
  # 备注
  remark: Json
  # 文件大小
  size: Int
  # 状态
  state: Int
  # 更新时间
  updatedAt: DateTime
  # 更新人
  updatedBy: Int
  # 权重
  weight: Int
}

# 对象存储供应商配置
type OssHost {
  # 访问凭证
  accessKey: String
  # 基础路径前缀
  basePath: String
  # 桶名称
  bucket: String
  # 创建时间
  createdAt: DateTime
  # 创建人
  createdBy: Int
  # 逻辑删除
  deletedAt: DateTime
  # 删除人
  deletedBy: Int
  # CDN域名
  domain: String
  # 主键
  id: ID!
  # 存储类型(aliyun/tencent/qiniu/local)
  kind: String
  # 区域
  region: String
  # 备注
  remark: Json
  # 访问密钥
  secretKey: String
  # 状态
  state: Int
  # 存储名称
  title: String
  # 更新时间
  updatedAt: DateTime
  # 更新人
  updatedBy: Int
  # 权重
  weight: Int
}

type Post {
  # 关联的Comment列表
  comments(where: CommentWhereInput, sort: [CommentSortInput!], limit: Int, offset: Int): [Comment]!
  content: String
  createdAt: DateTime!
  id: ID!
  # 关联的PostTag列表
  postPostTags(where: PostTagWhereInput, sort: [PostTagSortInput!], limit: Int, offset: Int): [PostTag]!
  # 关联的Tag列表
  tags(where: TagWhereInput, sort: [TagSortInput!], limit: Int, offset: Int): [Tag]!
  title: String!
  # 关联的User
  user: User!
  userId: ID!
}

type PostTag {
  # 关联的Post
  post: Post!
  postId: ID!
  # 关联的Tag
  tag: Tag!
  tagId: ID!
}

# 资源节点
type SysNode {
  # 是否固定标签
  affix: Boolean
  # 权限编码
  code: String
  # 组件路径
  component: String
  # 创建时间
  createdAt: DateTime
  # 创建人
  createdBy: Int
  # 逻辑删除
  deletedAt: DateTime
  # 删除人
  deletedBy: Int
  # 是否在导航中隐藏
  hidden: Boolean
  # 是否标记为首页
  home: Boolean
  # 图标
  icon: String
  # 主键
  id: ID!
  # 是否保持缓存
  keep: Boolean
  # 外链地址
  link: String
  # 请求方式(API 类型有效)
  method: String
  # 打开方式(iframe/window)
  mode: String
  # 路由名称
  name: String
  # 访问路径
  path: String
  # 父节点
  pid: Int
  # 备注
  remark: Json
  # 状态
  state: Int
  # 显示标题
  title: String
  # 节点类型(DIRECTORY/MENU/BUTTON/API)
  type: String
  # 更新时间
  updatedAt: DateTime
  # 更新人
  updatedBy: Int
  # 权重
  weight: Int
}

# 角色信息
type SysRole {
  # 名称
  code: String
  # 创建时间
  createdAt: DateTime
  # 创建人
  createdBy: Int
  # 逻辑删除
  deletedAt: DateTime
  # 删除人
  deletedBy: Int
  # 主键
  id: ID!
  # 名称
  name: String
  # 备注
  remark: Json
  # 数据范围
  scope: String
  # 状态
  state: Int
  # 更新时间
  updatedAt: DateTime
  # 更新人
  updatedBy: Int
  # 权重
  weight: Int
}

# 权限策略定义
type SysRule {
  deletedAt: DateTime
  # 主键
  id: ID!
  ptype: String
  v0: String
  v1: String
  v2: String
  v3: String
  v4: String
  v5: String
}

# 团队信息
type SysTeam {
  # 编码
  code: String
  # 创建时间
  createdAt: DateTime
  # 创建人
  createdBy: Int
  # 逻辑删除
  deletedAt: DateTime
  # 删除人
  deletedBy: Int
  # 主键
  id: ID!
  # 名称
  name: String
  # 父级
  pid: Int
  # 备注
  remark: Json
  # 状态
  state: Int
  # 更新时间
  updatedAt: DateTime
  # 更新人
  updatedBy: Int
  # 权重
  weight: Int
}

# 用户信息
type SysUser {
  # 头像
  avatar: String
  # 生日
  birthday: DateTime
  # 创建时间
  createdAt: DateTime
  # 创建人
  createdBy: Int
  # 逻辑删除
  deletedAt: DateTime
  # 删除人
  deletedBy: Int
  # 邮箱
  email: String
  # 性别
  gender: String
  # 主键
  id: ID!
  # 昵称
  nickname: String
  # 密码
  password: String
  # 手机号
  phone: String
  # 备注
  remark: Json
  # 来源
  source: String
  # 状态
  state: Int
  # 更新时间
  updatedAt: DateTime
  # 更新人
  updatedBy: Int
  # 名称
  username: String
  # 权重
  weight: Int
}

type Tag {
  id: ID!
  name: String!
  # 关联的Post列表
  posts(where: PostWhereInput, sort: [PostSortInput!], limit: Int, offset: Int): [Post]!
  # 关联的PostTag列表
  tagPostTags(where: PostTagWhereInput, sort: [PostTagSortInput!], limit: Int, offset: Int): [PostTag]!
}

type User {
  # 关联的Comment列表
  comments(where: CommentWhereInput, sort: [CommentSortInput!], limit: Int, offset: Int): [Comment]!
  createdAt: DateTime!
  email: String!
  id: ID!
  name: String!
  # 关联的Post列表
  posts(where: PostWhereInput, sort: [PostSortInput!], limit: Int, offset: Int): [Post]!
  profile: Json
}

# 游标分页信息
type PageInfo {
  hasNext: Boolean!
  hasPrev: Boolean!
  start: Cursor  # 本页第一条的游标
  end: Cursor  # 本页最后一条的游标
}

# ------------------ 连接和边类型（游标分页） ------------------

# AppHistory分页结果
type AppHistoryResult {
  items: [AppHistory!]!  # 直接返回AppHistory对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# AppLineage分页结果
type AppLineageResult {
  items: [AppLineage!]!  # 直接返回AppLineage对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# Comment分页结果
type CommentResult {
  items: [Comment!]!  # 直接返回Comment对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# OssFile分页结果
type OssFileResult {
  items: [OssFile!]!  # 直接返回OssFile对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# OssHost分页结果
type OssHostResult {
  items: [OssHost!]!  # 直接返回OssHost对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# Post分页结果
type PostResult {
  items: [Post!]!  # 直接返回Post对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# PostTag分页结果
type PostTagResult {
  items: [PostTag!]!  # 直接返回PostTag对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# SysNode分页结果
type SysNodeResult {
  items: [SysNode!]!  # 直接返回SysNode对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# SysRole分页结果
type SysRoleResult {
  items: [SysRole!]!  # 直接返回SysRole对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# SysRule分页结果
type SysRuleResult {
  items: [SysRule!]!  # 直接返回SysRule对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# SysTeam分页结果
type SysTeamResult {
  items: [SysTeam!]!  # 直接返回SysTeam对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# SysUser分页结果
type SysUserResult {
  items: [SysUser!]!  # 直接返回SysUser对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# Tag分页结果
type TagResult {
  items: [Tag!]!  # 直接返回Tag对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# User分页结果
type UserResult {
  items: [User!]!  # 直接返回User对象数组
  total: Int!
  pageInfo: PageInfo  # 游标分页信息(需配合first/last使用)
}

# 数值聚合结果
type NumberStats {
  sum: Float
  avg: Float
  min: Float
  max: Float
  countDistinct: Int
}

# 字符串聚合结果
type StringStats {
  min: String
  max: String
  countDistinct: Int
}

# 日期聚合结果
type DateTimeStats {
  min: DateTime
  max: DateTime
  countDistinct: Int
}

# 数值聚合having过滤
input NumberHaving {
  sum: FloatWhereInput
  avg: FloatWhereInput
  min: FloatWhereInput
  max: FloatWhereInput
  countDistinct: IntWhereInput
}

# 字符串聚合having过滤
input StringHaving {
  min: StringWhereInput
  max: StringWhereInput
  countDistinct: IntWhereInput
}

# 日期聚合having过滤
input DateTimeHaving {
  min: DateTimeWhereInput
  max: DateTimeWhereInput
  countDistinct: IntWhereInput
}

# AppHistory统计结果
type AppHistoryStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  authorId: NumberStats
  changeNote: StringStats
  createdAt: DateTimeStats
  createdBy: NumberStats
  deletedAt: DateTimeStats
  deletedBy: NumberStats
  editorId: NumberStats
  lineageId: NumberStats
  publishAt: DateTimeStats
  state: NumberStats
  updatedAt: DateTimeStats
  updatedBy: NumberStats
  version: NumberStats
  weight: NumberStats
}

# AppHistoryhaving过滤(分组后按聚合值过滤)
input AppHistoryHavingInput {
  count: IntWhereInput
  authorId: NumberHaving
  changeNote: StringHaving
  createdAt: DateTimeHaving
  createdBy: NumberHaving
  deletedAt: DateTimeHaving
  deletedBy: NumberHaving
  editorId: NumberHaving
  lineageId: NumberHaving
  publishAt: DateTimeHaving
  state: NumberHaving
  updatedAt: DateTimeHaving
  updatedBy: NumberHaving
  version: NumberHaving
  weight: NumberHaving
}

# AppLineage统计结果
type AppLineageStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  cover: StringStats
  createdAt: DateTimeStats
  createdBy: NumberStats
  deletedAt: DateTimeStats
  deletedBy: NumberStats
  difficulty: NumberStats
  icon: StringStats
  latin: StringStats
  pid: NumberStats
  publishAt: DateTimeStats
  state: NumberStats
  title: StringStats
  updatedAt: DateTimeStats
  updatedBy: NumberStats
  version: NumberStats
  weight: NumberStats
}

# AppLineagehaving过滤(分组后按聚合值过滤)
input AppLineageHavingInput {
  count: IntWhereInput
  cover: StringHaving
  createdAt: DateTimeHaving
  createdBy: NumberHaving
  deletedAt: DateTimeHaving
  deletedBy: NumberHaving
  difficulty: NumberHaving
  icon: StringHaving
  latin: StringHaving
  pid: NumberHaving
  publishAt: DateTimeHaving
  state: NumberHaving
  title: StringHaving
  updatedAt: DateTimeHaving
  updatedBy: NumberHaving
  version: NumberHaving
  weight: NumberHaving
}

# Comment统计结果
type CommentStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  content: StringStats
  createdAt: DateTimeStats
}

# Commenthaving过滤(分组后按聚合值过滤)
input CommentHavingInput {
  count: IntWhereInput
  content: StringHaving
  createdAt: DateTimeHaving
}

# OssFile统计结果
type OssFileStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  createdAt: DateTimeStats
  createdBy: NumberStats
  deletedAt: DateTimeStats
  deletedBy: NumberStats
  filename: StringStats
  hash: StringStats
  hostId: NumberStats
  ip: StringStats
  mimeType: StringStats
  objectKey: StringStats
  size: NumberStats
  state: NumberStats
  updatedAt: DateTimeStats
  updatedBy: NumberStats
  weight: NumberStats
}

# OssFilehaving过滤(分组后按聚合值过滤)
input OssFileHavingInput {
  count: IntWhereInput
  createdAt: DateTimeHaving
  createdBy: NumberHaving
  deletedAt: DateTimeHaving
  deletedBy: NumberHaving
  filename: StringHaving
  hash: StringHaving
  hostId: NumberHaving
  ip: StringHaving
  mimeType: StringHaving
  objectKey: StringHaving
  size: NumberHaving
  state: NumberHaving
  updatedAt: DateTimeHaving
  updatedBy: NumberHaving
  weight: NumberHaving
}

# OssHost统计结果
type OssHostStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  accessKey: StringStats
  basePath: StringStats
  bucket: StringStats
  createdAt: DateTimeStats
  createdBy: NumberStats
  deletedAt: DateTimeStats
  deletedBy: NumberStats
  domain: StringStats
  kind: StringStats
  region: StringStats
  secretKey: StringStats
  state: NumberStats
  title: StringStats
  updatedAt: DateTimeStats
  updatedBy: NumberStats
  weight: NumberStats
}

# OssHosthaving过滤(分组后按聚合值过滤)
input OssHostHavingInput {
  count: IntWhereInput
  accessKey: StringHaving
  basePath: StringHaving
  bucket: StringHaving
  createdAt: DateTimeHaving
  createdBy: NumberHaving
  deletedAt: DateTimeHaving
  deletedBy: NumberHaving
  domain: StringHaving
  kind: StringHaving
  region: StringHaving
  secretKey: StringHaving
  state: NumberHaving
  title: StringHaving
  updatedAt: DateTimeHaving
  updatedBy: NumberHaving
  weight: NumberHaving
}

# Post统计结果
type PostStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  content: StringStats
  createdAt: DateTimeStats
  title: StringStats
}

# Posthaving过滤(分组后按聚合值过滤)
input PostHavingInput {
  count: IntWhereInput
  content: StringHaving
  createdAt: DateTimeHaving
  title: StringHaving
}

# PostTag统计结果
type PostTagStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
}

# PostTaghaving过滤(分组后按聚合值过滤)
input PostTagHavingInput {
  count: IntWhereInput
}

# SysNode统计结果
type SysNodeStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  code: StringStats
  component: StringStats
  createdAt: DateTimeStats
  createdBy: NumberStats
  deletedAt: DateTimeStats
  deletedBy: NumberStats
  icon: StringStats
  link: StringStats
  method: StringStats
  mode: StringStats
  name: StringStats
  path: StringStats
  pid: NumberStats
  state: NumberStats
  title: StringStats
  type: StringStats
  updatedAt: DateTimeStats
  updatedBy: NumberStats
  weight: NumberStats
}

# SysNodehaving过滤(分组后按聚合值过滤)
input SysNodeHavingInput {
  count: IntWhereInput
  code: StringHaving
  component: StringHaving
  createdAt: DateTimeHaving
  createdBy: NumberHaving
  deletedAt: DateTimeHaving
  deletedBy: NumberHaving
  icon: StringHaving
  link: StringHaving
  method: StringHaving
  mode: StringHaving
  name: StringHaving
  path: StringHaving
  pid: NumberHaving
  state: NumberHaving
  title: StringHaving
  type: StringHaving
  updatedAt: DateTimeHaving
  updatedBy: NumberHaving
  weight: NumberHaving
}

# SysRole统计结果
type SysRoleStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  code: StringStats
  createdAt: DateTimeStats
  createdBy: NumberStats
  deletedAt: DateTimeStats
  deletedBy: NumberStats
  name: StringStats
  scope: StringStats
  state: NumberStats
  updatedAt: DateTimeStats
  updatedBy: NumberStats
  weight: NumberStats
}

# SysRolehaving过滤(分组后按聚合值过滤)
input SysRoleHavingInput {
  count: IntWhereInput
  code: StringHaving
  createdAt: DateTimeHaving
  createdBy: NumberHaving
  deletedAt: DateTimeHaving
  deletedBy: NumberHaving
  name: StringHaving
  scope: StringHaving
  state: NumberHaving
  updatedAt: DateTimeHaving
  updatedBy: NumberHaving
  weight: NumberHaving
}

# SysRule统计结果
type SysRuleStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  deletedAt: DateTimeStats
  ptype: StringStats
  v0: StringStats
  v1: StringStats
  v2: StringStats
  v3: StringStats
  v4: StringStats
  v5: StringStats
}

# SysRulehaving过滤(分组后按聚合值过滤)
input SysRuleHavingInput {
  count: IntWhereInput
  deletedAt: DateTimeHaving
  ptype: StringHaving
  v0: StringHaving
  v1: StringHaving
  v2: StringHaving
  v3: StringHaving
  v4: StringHaving
  v5: StringHaving
}

# SysTeam统计结果
type SysTeamStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  code: StringStats
  createdAt: DateTimeStats
  createdBy: NumberStats
  deletedAt: DateTimeStats
  deletedBy: NumberStats
  name: StringStats
  pid: NumberStats
  state: NumberStats
  updatedAt: DateTimeStats
  updatedBy: NumberStats
  weight: NumberStats
}

# SysTeamhaving过滤(分组后按聚合值过滤)
input SysTeamHavingInput {
  count: IntWhereInput
  code: StringHaving
  createdAt: DateTimeHaving
  createdBy: NumberHaving
  deletedAt: DateTimeHaving
  deletedBy: NumberHaving
  name: StringHaving
  pid: NumberHaving
  state: NumberHaving
  updatedAt: DateTimeHaving
  updatedBy: NumberHaving
  weight: NumberHaving
}

# SysUser统计结果
type SysUserStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  avatar: StringStats
  birthday: DateTimeStats
  createdAt: DateTimeStats
  createdBy: NumberStats
  deletedAt: DateTimeStats
  deletedBy: NumberStats
  email: StringStats
  gender: StringStats
  nickname: StringStats
  password: StringStats
  phone: StringStats
  source: StringStats
  state: NumberStats
  updatedAt: DateTimeStats
  updatedBy: NumberStats
  username: StringStats
  weight: NumberStats
}

# SysUserhaving过滤(分组后按聚合值过滤)
input SysUserHavingInput {
  count: IntWhereInput
  avatar: StringHaving
  birthday: DateTimeHaving
  createdAt: DateTimeHaving
  createdBy: NumberHaving
  deletedAt: DateTimeHaving
  deletedBy: NumberHaving
  email: StringHaving
  gender: StringHaving
  nickname: StringHaving
  password: StringHaving
  phone: StringHaving
  source: StringHaving
  state: NumberHaving
  updatedAt: DateTimeHaving
  updatedBy: NumberHaving
  username: StringHaving
  weight: NumberHaving
}

# Tag统计结果
type TagStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  name: StringStats
}

# Taghaving过滤(分组后按聚合值过滤)
input TagHavingInput {
  count: IntWhereInput
  name: StringHaving
}

# User统计结果
type UserStats {
  key: Json  # 分组键(无groupBy时为null)
  count: Int!
  createdAt: DateTimeStats
  email: StringStats
  name: StringStats
}

# Userhaving过滤(分组后按聚合值过滤)
input UserHavingInput {
  count: IntWhereInput
  createdAt: DateTimeHaving
  email: StringHaving
  name: StringHaving
}

# ------------------ 过滤器类型定义 ------------------

# Boolean过滤器
input BooleanWhereInput {
  eq: Boolean  # Equals value
  in: [Boolean!]  # Is in list of values
}

# DateTime过滤器
input DateTimeWhereInput {
  is: IsInput  # Is value null (true) or not null (false)
  eq: DateTime  # Equals value
  in: [DateTime!]  # Is in list of values
  gt: DateTime  # Is greater than value
  ge: DateTime  # Is greater than or equal to value
  lt: DateTime  # Is less than value
  le: DateTime  # Is less than or equal to value
  ne: DateTime  # Does not equal value
}

# Float过滤器
input FloatWhereInput {
  is: IsInput  # Is value null (true) or not null (false)
  eq: Float  # Equals value
  in: [Float!]  # Is in list of values
  gt: Float  # Is greater than value
  ge: Float  # Is greater than or equal to value
  lt: Float  # Is less than value
  le: Float  # Is less than or equal to value
  ne: Float  # Does not equal value
}

# ID过滤器
input IDWhereInput {
  eq: ID  # Equals value
  in: [ID!]  # Is in list of values
  gt: ID  # Is greater than value
  ge: ID  # Is greater than or equal to value
  lt: ID  # Is less than value
  le: ID  # Is less than or equal to value
}

# Int过滤器
input IntWhereInput {
  is: IsInput  # Is value null (true) or not null (false)
  eq: Int  # Equals value
  in: [Int!]  # Is in list of values
  gt: Int  # Is greater than value
  ge: Int  # Is greater than or equal to value
  lt: Int  # Is less than value
  le: Int  # Is less than or equal to value
  ne: Int  # Does not equal value
}

# Json过滤器
input JsonWhereInput {
  is: IsInput  # Is value null (true) or not null (false)
  eq: Json  # Equals value
  in: [Json!]  # Is in list of values
  contains: Json  # JSON value contains the given JSON (jsonb @>, GIN-indexable)
  containedIn: Json  # JSON value is contained in the given JSON (jsonb <@)
  hasKey: String  # Value is a JSON object with the specified key
}

# String过滤器
input StringWhereInput {
  is: IsInput  # Is value null (true) or not null (false)
  eq: String  # Equals value
  in: [String!]  # Is in list of values
  gt: String  # Is greater than value
  ge: String  # Is greater than or equal to value
  lt: String  # Is less than value
  le: String  # Is less than or equal to value
  ne: String  # Does not equal value
  like: String  # Value matching pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values having 'r' in second position
  iLike: String  # Value matching (case-insensitive) pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values not having 'r' in second position
  regex: String  # Value matching regular pattern
  iRegex: String  # Value matching (case-insensitive) regex pattern
}

# AppHistory查询条件
input AppHistoryWhereInput {
  authorId: IntWhereInput
  changeNote: StringWhereInput
  createdAt: DateTimeWhereInput
  createdBy: IntWhereInput
  deletedAt: DateTimeWhereInput
  deletedBy: IntWhereInput
  editorId: IntWhereInput
  id: IDWhereInput
  lineageId: IntWhereInput
  payload: JsonWhereInput
  publishAt: DateTimeWhereInput
  remark: JsonWhereInput
  state: IntWhereInput
  updatedAt: DateTimeWhereInput
  updatedBy: IntWhereInput
  version: IntWhereInput
  weight: IntWhereInput
  and: [AppHistoryWhereInput!]
  or: [AppHistoryWhereInput!]
  not: AppHistoryWhereInput
}

# AppLineage查询条件
input AppLineageWhereInput {
  alias: JsonWhereInput
  cover: StringWhereInput
  createdAt: DateTimeWhereInput
  createdBy: IntWhereInput
  deletedAt: DateTimeWhereInput
  deletedBy: IntWhereInput
  difficulty: IntWhereInput
  draft: JsonWhereInput
  environment: JsonWhereInput
  icon: StringWhereInput
  id: IDWhereInput
  latin: StringWhereInput
  payload: JsonWhereInput
  pid: IntWhereInput
  publishAt: DateTimeWhereInput
  relationship: JsonWhereInput
  remark: JsonWhereInput
  state: IntWhereInput
  title: StringWhereInput
  updatedAt: DateTimeWhereInput
  updatedBy: IntWhereInput
  version: IntWhereInput
  weight: IntWhereInput
  and: [AppLineageWhereInput!]
  or: [AppLineageWhereInput!]
  not: AppLineageWhereInput
}

# Comment查询条件
input CommentWhereInput {
  content: StringWhereInput
  createdAt: DateTimeWhereInput
  id: IDWhereInput
  parentId: IDWhereInput
  postId: IDWhereInput
  userId: IDWhereInput
  and: [CommentWhereInput!]
  or: [CommentWhereInput!]
  not: CommentWhereInput
}

# OssFile查询条件
input OssFileWhereInput {
  createdAt: DateTimeWhereInput
  createdBy: IntWhereInput
  deletedAt: DateTimeWhereInput
  deletedBy: IntWhereInput
  filename: StringWhereInput
  hash: StringWhereInput
  hostId: IntWhereInput
  id: IDWhereInput
  ip: StringWhereInput
  mimeType: StringWhereInput
  objectKey: StringWhereInput
  remark: JsonWhereInput
  size: IntWhereInput
  state: IntWhereInput
  updatedAt: DateTimeWhereInput
  updatedBy: IntWhereInput
  weight: IntWhereInput
  and: [OssFileWhereInput!]
  or: [OssFileWhereInput!]
  not: OssFileWhereInput
}

# OssHost查询条件
input OssHostWhereInput {
  accessKey: StringWhereInput
  basePath: StringWhereInput
  bucket: StringWhereInput
  createdAt: DateTimeWhereInput
  createdBy: IntWhereInput
  deletedAt: DateTimeWhereInput
  deletedBy: IntWhereInput
  domain: StringWhereInput
  id: IDWhereInput
  kind: StringWhereInput
  region: StringWhereInput
  remark: JsonWhereInput
  secretKey: StringWhereInput
  state: IntWhereInput
  title: StringWhereInput
  updatedAt: DateTimeWhereInput
  updatedBy: IntWhereInput
  weight: IntWhereInput
  and: [OssHostWhereInput!]
  or: [OssHostWhereInput!]
  not: OssHostWhereInput
}

# Post查询条件
input PostWhereInput {
  content: StringWhereInput
  createdAt: DateTimeWhereInput
  id: IDWhereInput
  title: StringWhereInput
  userId: IDWhereInput
  and: [PostWhereInput!]
  or: [PostWhereInput!]
  not: PostWhereInput
}

# PostTag查询条件
input PostTagWhereInput {
  postId: IDWhereInput
  tagId: IDWhereInput
  and: [PostTagWhereInput!]
  or: [PostTagWhereInput!]
  not: PostTagWhereInput
}

# SysNode查询条件
input SysNodeWhereInput {
  affix: BooleanWhereInput
  code: StringWhereInput
  component: StringWhereInput
  createdAt: DateTimeWhereInput
  createdBy: IntWhereInput
  deletedAt: DateTimeWhereInput
  deletedBy: IntWhereInput
  hidden: BooleanWhereInput
  home: BooleanWhereInput
  icon: StringWhereInput
  id: IDWhereInput
  keep: BooleanWhereInput
  link: StringWhereInput
  method: StringWhereInput
  mode: StringWhereInput
  name: StringWhereInput
  path: StringWhereInput
  pid: IntWhereInput
  remark: JsonWhereInput
  state: IntWhereInput
  title: StringWhereInput
  type: StringWhereInput
  updatedAt: DateTimeWhereInput
  updatedBy: IntWhereInput
  weight: IntWhereInput
  and: [SysNodeWhereInput!]
  or: [SysNodeWhereInput!]
  not: SysNodeWhereInput
}

# SysRole查询条件
input SysRoleWhereInput {
  code: StringWhereInput
  createdAt: DateTimeWhereInput
  createdBy: IntWhereInput
  deletedAt: DateTimeWhereInput
  deletedBy: IntWhereInput
  id: IDWhereInput
  name: StringWhereInput
  remark: JsonWhereInput
  scope: StringWhereInput
  state: IntWhereInput
  updatedAt: DateTimeWhereInput
  updatedBy: IntWhereInput
  weight: IntWhereInput
  and: [SysRoleWhereInput!]
  or: [SysRoleWhereInput!]
  not: SysRoleWhereInput
}

# SysRule查询条件
input SysRuleWhereInput {
  deletedAt: DateTimeWhereInput
  id: IDWhereInput
  ptype: StringWhereInput
  v0: StringWhereInput
  v1: StringWhereInput
  v2: StringWhereInput
  v3: StringWhereInput
  v4: StringWhereInput
  v5: StringWhereInput
  and: [SysRuleWhereInput!]
  or: [SysRuleWhereInput!]
  not: SysRuleWhereInput
}

# SysTeam查询条件
input SysTeamWhereInput {
  code: StringWhereInput
  createdAt: DateTimeWhereInput
  createdBy: IntWhereInput
  deletedAt: DateTimeWhereInput
  deletedBy: IntWhereInput
  id: IDWhereInput
  name: StringWhereInput
  pid: IntWhereInput
  remark: JsonWhereInput
  state: IntWhereInput
  updatedAt: DateTimeWhereInput
  updatedBy: IntWhereInput
  weight: IntWhereInput
  and: [SysTeamWhereInput!]
  or: [SysTeamWhereInput!]
  not: SysTeamWhereInput
}

# SysUser查询条件
input SysUserWhereInput {
  avatar: StringWhereInput
  birthday: DateTimeWhereInput
  createdAt: DateTimeWhereInput
  createdBy: IntWhereInput
  deletedAt: DateTimeWhereInput
  deletedBy: IntWhereInput
  email: StringWhereInput
  gender: StringWhereInput
  id: IDWhereInput
  nickname: StringWhereInput
  password: StringWhereInput
  phone: StringWhereInput
  remark: JsonWhereInput
  source: StringWhereInput
  state: IntWhereInput
  updatedAt: DateTimeWhereInput
  updatedBy: IntWhereInput
  username: StringWhereInput
  weight: IntWhereInput
  and: [SysUserWhereInput!]
  or: [SysUserWhereInput!]
  not: SysUserWhereInput
}

# Tag查询条件
input TagWhereInput {
  id: IDWhereInput
  name: StringWhereInput
  and: [TagWhereInput!]
  or: [TagWhereInput!]
  not: TagWhereInput
}

# User查询条件
input UserWhereInput {
  createdAt: DateTimeWhereInput
  email: StringWhereInput
  id: IDWhereInput
  name: StringWhereInput
  profile: JsonWhereInput
  and: [UserWhereInput!]
  or: [UserWhereInput!]
  not: UserWhereInput
}

# AppHistory排序
input AppHistorySortInput {
  authorId: SortDirection
  changeNote: SortDirection
  createdAt: SortDirection
  createdBy: SortDirection
  deletedAt: SortDirection
  deletedBy: SortDirection
  editorId: SortDirection
  id: SortDirection
  lineageId: SortDirection
  payload: SortDirection
  publishAt: SortDirection
  remark: SortDirection
  state: SortDirection
  updatedAt: SortDirection
  updatedBy: SortDirection
  version: SortDirection
  weight: SortDirection
}

# AppLineage排序
input AppLineageSortInput {
  alias: SortDirection
  cover: SortDirection
  createdAt: SortDirection
  createdBy: SortDirection
  deletedAt: SortDirection
  deletedBy: SortDirection
  difficulty: SortDirection
  draft: SortDirection
  environment: SortDirection
  icon: SortDirection
  id: SortDirection
  latin: SortDirection
  payload: SortDirection
  pid: SortDirection
  publishAt: SortDirection
  relationship: SortDirection
  remark: SortDirection
  state: SortDirection
  title: SortDirection
  updatedAt: SortDirection
  updatedBy: SortDirection
  version: SortDirection
  weight: SortDirection
}

# Comment排序
input CommentSortInput {
  content: SortDirection
  createdAt: SortDirection
  id: SortDirection
  parentId: SortDirection
  postId: SortDirection
  userId: SortDirection
}

# OssFile排序
input OssFileSortInput {
  createdAt: SortDirection
  createdBy: SortDirection
  deletedAt: SortDirection
  deletedBy: SortDirection
  filename: SortDirection
  hash: SortDirection
  hostId: SortDirection
  id: SortDirection
  ip: SortDirection
  mimeType: SortDirection
  objectKey: SortDirection
  remark: SortDirection
  size: SortDirection
  state: SortDirection
  updatedAt: SortDirection
  updatedBy: SortDirection
  weight: SortDirection
}

# OssHost排序
input OssHostSortInput {
  accessKey: SortDirection
  basePath: SortDirection
  bucket: SortDirection
  createdAt: SortDirection
  createdBy: SortDirection
  deletedAt: SortDirection
  deletedBy: SortDirection
  domain: SortDirection
  id: SortDirection
  kind: SortDirection
  region: SortDirection
  remark: SortDirection
  secretKey: SortDirection
  state: SortDirection
  title: SortDirection
  updatedAt: SortDirection
  updatedBy: SortDirection
  weight: SortDirection
}

# Post排序
input PostSortInput {
  content: SortDirection
  createdAt: SortDirection
  id: SortDirection
  title: SortDirection
  userId: SortDirection
}

# PostTag排序
input PostTagSortInput {
  postId: SortDirection
  tagId: SortDirection
}

# SysNode排序
input SysNodeSortInput {
  affix: SortDirection
  code: SortDirection
  component: SortDirection
  createdAt: SortDirection
  createdBy: SortDirection
  deletedAt: SortDirection
  deletedBy: SortDirection
  hidden: SortDirection
  home: SortDirection
  icon: SortDirection
  id: SortDirection
  keep: SortDirection
  link: SortDirection
  method: SortDirection
  mode: SortDirection
  name: SortDirection
  path: SortDirection
  pid: SortDirection
  remark: SortDirection
  state: SortDirection
  title: SortDirection
  type: SortDirection
  updatedAt: SortDirection
  updatedBy: SortDirection
  weight: SortDirection
}

# SysRole排序
input SysRoleSortInput {
  code: SortDirection
  createdAt: SortDirection
  createdBy: SortDirection
  deletedAt: SortDirection
  deletedBy: SortDirection
  id: SortDirection
  name: SortDirection
  remark: SortDirection
  scope: SortDirection
  state: SortDirection
  updatedAt: SortDirection
  updatedBy: SortDirection
  weight: SortDirection
}

# SysRule排序
input SysRuleSortInput {
  deletedAt: SortDirection
  id: SortDirection
  ptype: SortDirection
  v0: SortDirection
  v1: SortDirection
  v2: SortDirection
  v3: SortDirection
  v4: SortDirection
  v5: SortDirection
}

# SysTeam排序
input SysTeamSortInput {
  code: SortDirection
  createdAt: SortDirection
  createdBy: SortDirection
  deletedAt: SortDirection
  deletedBy: SortDirection
  id: SortDirection
  name: SortDirection
  pid: SortDirection
  remark: SortDirection
  state: SortDirection
  updatedAt: SortDirection
  updatedBy: SortDirection
  weight: SortDirection
}

# SysUser排序
input SysUserSortInput {
  avatar: SortDirection
  birthday: SortDirection
  createdAt: SortDirection
  createdBy: SortDirection
  deletedAt: SortDirection
  deletedBy: SortDirection
  email: SortDirection
  gender: SortDirection
  id: SortDirection
  nickname: SortDirection
  password: SortDirection
  phone: SortDirection
  remark: SortDirection
  source: SortDirection
  state: SortDirection
  updatedAt: SortDirection
  updatedBy: SortDirection
  username: SortDirection
  weight: SortDirection
}

# Tag排序
input TagSortInput {
  id: SortDirection
  name: SortDirection
}

# User排序
input UserSortInput {
  createdAt: SortDirection
  email: SortDirection
  id: SortDirection
  name: SortDirection
  profile: SortDirection
}

# AppHistory创建输入
input AppHistoryCreateInput {
  authorId: Int
  changeNote: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  editorId: Int
  lineageId: Int
  payload: Json
  publishAt: DateTime
  remark: Json
  state: Int
  updatedBy: Int
  version: Int
  weight: Int
}

# AppHistory更新输入
input AppHistoryUpdateInput {
  authorId: Int
  changeNote: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  editorId: Int
  lineageId: Int
  payload: Json
  publishAt: DateTime
  remark: Json
  state: Int
  updatedBy: Int
  version: Int
  weight: Int
}

# AppLineage创建输入
input AppLineageCreateInput {
  alias: Json
  cover: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  difficulty: Int
  draft: Json
  environment: Json
  icon: String
  latin: String
  payload: Json
  pid: Int
  publishAt: DateTime
  relationship: Json
  remark: Json
  state: Int
  title: String
  updatedBy: Int
  version: Int
  weight: Int
}

# AppLineage更新输入
input AppLineageUpdateInput {
  alias: Json
  cover: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  difficulty: Int
  draft: Json
  environment: Json
  icon: String
  latin: String
  payload: Json
  pid: Int
  publishAt: DateTime
  relationship: Json
  remark: Json
  state: Int
  title: String
  updatedBy: Int
  version: Int
  weight: Int
}

# Comment创建输入
input CommentCreateInput {
  content: String!
  parentId: ID
  postId: ID
  userId: ID
  ancestors: CommentRelationInput
  children: CommentRelationInput
  descendants: CommentRelationInput
}

# Comment更新输入
input CommentUpdateInput {
  content: String
  parentId: ID
  postId: ID
  userId: ID
  ancestors: CommentRelationInput
  children: CommentRelationInput
  descendants: CommentRelationInput
}

# OssFile创建输入
input OssFileCreateInput {
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  filename: String
  hash: String
  hostId: Int
  ip: String
  mimeType: String
  objectKey: String
  remark: Json
  size: Int
  state: Int
  updatedBy: Int
  weight: Int
}

# OssFile更新输入
input OssFileUpdateInput {
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  filename: String
  hash: String
  hostId: Int
  ip: String
  mimeType: String
  objectKey: String
  remark: Json
  size: Int
  state: Int
  updatedBy: Int
  weight: Int
}

# OssHost创建输入
input OssHostCreateInput {
  accessKey: String
  basePath: String
  bucket: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  domain: String
  kind: String
  region: String
  remark: Json
  secretKey: String
  state: Int
  title: String
  updatedBy: Int
  weight: Int
}

# OssHost更新输入
input OssHostUpdateInput {
  accessKey: String
  basePath: String
  bucket: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  domain: String
  kind: String
  region: String
  remark: Json
  secretKey: String
  state: Int
  title: String
  updatedBy: Int
  weight: Int
}

# Post创建输入
input PostCreateInput {
  content: String
  title: String!
  userId: ID
  comments: CommentRelationInput
  postPostTags: PostTagRelationInput
  tags: TagRelationInput
}

# Post更新输入
input PostUpdateInput {
  content: String
  title: String
  userId: ID
  comments: CommentRelationInput
  postPostTags: PostTagRelationInput
  tags: TagRelationInput
}

# SysNode创建输入
input SysNodeCreateInput {
  affix: Boolean
  code: String
  component: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  hidden: Boolean
  home: Boolean
  icon: String
  keep: Boolean
  link: String
  method: String
  mode: String
  name: String
  path: String
  pid: Int
  remark: Json
  state: Int
  title: String
  type: String
  updatedBy: Int
  weight: Int
}

# SysNode更新输入
input SysNodeUpdateInput {
  affix: Boolean
  code: String
  component: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  hidden: Boolean
  home: Boolean
  icon: String
  keep: Boolean
  link: String
  method: String
  mode: String
  name: String
  path: String
  pid: Int
  remark: Json
  state: Int
  title: String
  type: String
  updatedBy: Int
  weight: Int
}

# SysRole创建输入
input SysRoleCreateInput {
  code: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  name: String
  remark: Json
  scope: String
  state: Int
  updatedBy: Int
  weight: Int
}

# SysRole更新输入
input SysRoleUpdateInput {
  code: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  name: String
  remark: Json
  scope: String
  state: Int
  updatedBy: Int
  weight: Int
}

# SysRule创建输入
input SysRuleCreateInput {
  deletedAt: DateTime
  ptype: String
  v0: String
  v1: String
  v2: String
  v3: String
  v4: String
  v5: String
}

# SysRule更新输入
input SysRuleUpdateInput {
  deletedAt: DateTime
  ptype: String
  v0: String
  v1: String
  v2: String
  v3: String
  v4: String
  v5: String
}

# SysTeam创建输入
input SysTeamCreateInput {
  code: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  name: String
  pid: Int
  remark: Json
  state: Int
  updatedBy: Int
  weight: Int
}

# SysTeam更新输入
input SysTeamUpdateInput {
  code: String
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  name: String
  pid: Int
  remark: Json
  state: Int
  updatedBy: Int
  weight: Int
}

# SysUser创建输入
input SysUserCreateInput {
  avatar: String
  birthday: DateTime
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  email: String
  gender: String
  nickname: String
  password: String
  phone: String
  remark: Json
  source: String
  state: Int
  updatedBy: Int
  username: String
  weight: Int
}

# SysUser更新输入
input SysUserUpdateInput {
  avatar: String
  birthday: DateTime
  createdBy: Int
  deletedAt: DateTime
  deletedBy: Int
  email: String
  gender: String
  nickname: String
  password: String
  phone: String
  remark: Json
  source: String
  state: Int
  updatedBy: Int
  username: String
  weight: Int
}

# Tag创建输入
input TagCreateInput {
  name: String!
  posts: PostRelationInput
  tagPostTags: PostTagRelationInput
}

# Tag更新输入
input TagUpdateInput {
  name: String
  posts: PostRelationInput
  tagPostTags: PostTagRelationInput
}

# User创建输入
input UserCreateInput {
  email: String!
  name: String!
  profile: Json
  comments: CommentRelationInput
  posts: PostRelationInput
}

# User更新输入
input UserUpdateInput {
  email: String
  name: String
  profile: Json
  comments: CommentRelationInput
  posts: PostRelationInput
}

# AppHistory关系操作（原子挂接/解除/内联创建）
input AppHistoryRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [AppHistoryCreateInput!]  # 内联创建新行
}

# AppLineage关系操作（原子挂接/解除/内联创建）
input AppLineageRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [AppLineageCreateInput!]  # 内联创建新行
}

# Comment关系操作（原子挂接/解除/内联创建）
input CommentRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [CommentCreateInput!]  # 内联创建新行
}

# OssFile关系操作（原子挂接/解除/内联创建）
input OssFileRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [OssFileCreateInput!]  # 内联创建新行
}

# OssHost关系操作（原子挂接/解除/内联创建）
input OssHostRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [OssHostCreateInput!]  # 内联创建新行
}

# Post关系操作（原子挂接/解除/内联创建）
input PostRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [PostCreateInput!]  # 内联创建新行
}

# PostTag关系操作（原子挂接/解除/内联创建）
input PostTagRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
}

# SysNode关系操作（原子挂接/解除/内联创建）
input SysNodeRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [SysNodeCreateInput!]  # 内联创建新行
}

# SysRole关系操作（原子挂接/解除/内联创建）
input SysRoleRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [SysRoleCreateInput!]  # 内联创建新行
}

# SysRule关系操作（原子挂接/解除/内联创建）
input SysRuleRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [SysRuleCreateInput!]  # 内联创建新行
}

# SysTeam关系操作（原子挂接/解除/内联创建）
input SysTeamRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [SysTeamCreateInput!]  # 内联创建新行
}

# SysUser关系操作（原子挂接/解除/内联创建）
input SysUserRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [SysUserCreateInput!]  # 内联创建新行
}

# Tag关系操作（原子挂接/解除/内联创建）
input TagRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [TagCreateInput!]  # 内联创建新行
}

# User关系操作（原子挂接/解除/内联创建）
input UserRelationInput {
  connect: [ID!]  # 挂接既有行主键
  disconnect: [ID!]  # 解除既有行主键(仅更新)
  create: [UserCreateInput!]  # 内联创建新行
}

# ------------------ 查询和变更 ------------------

# 查询根类型
type Query {
  # AppHistory查询
  appHistories(
    id: ID
    where: AppHistoryWhereInput
    sort: [AppHistorySortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): AppHistoryResult!
  # AppHistory统计
  appHistoryStats(where: AppHistoryWhereInput, groupBy: [String!], having: AppHistoryHavingInput, limit: Int, offset: Int): [AppHistoryStats!]!
  # AppLineage查询
  appLineages(
    id: ID
    where: AppLineageWhereInput
    sort: [AppLineageSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): AppLineageResult!
  # AppLineage统计
  appLineageStats(where: AppLineageWhereInput, groupBy: [String!], having: AppLineageHavingInput, limit: Int, offset: Int): [AppLineageStats!]!
  # Comment查询
  comments(
    id: ID
    where: CommentWhereInput
    sort: [CommentSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): CommentResult!
  # Comment统计
  commentStats(where: CommentWhereInput, groupBy: [String!], having: CommentHavingInput, limit: Int, offset: Int): [CommentStats!]!
  # OssFile查询
  ossFiles(
    id: ID
    where: OssFileWhereInput
    sort: [OssFileSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): OssFileResult!
  # OssFile统计
  ossFileStats(where: OssFileWhereInput, groupBy: [String!], having: OssFileHavingInput, limit: Int, offset: Int): [OssFileStats!]!
  # OssHost查询
  ossHosts(
    id: ID
    where: OssHostWhereInput
    sort: [OssHostSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): OssHostResult!
  # OssHost统计
  ossHostStats(where: OssHostWhereInput, groupBy: [String!], having: OssHostHavingInput, limit: Int, offset: Int): [OssHostStats!]!
  # Post查询
  posts(
    search: String
    id: ID
    where: PostWhereInput
    sort: [PostSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): PostResult!
  # Post统计
  postStats(where: PostWhereInput, groupBy: [String!], having: PostHavingInput, limit: Int, offset: Int): [PostStats!]!
  # PostTag查询
  postTags(
    id: ID
    where: PostTagWhereInput
    sort: [PostTagSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): PostTagResult!
  # PostTag统计
  postTagStats(where: PostTagWhereInput, groupBy: [String!], having: PostTagHavingInput, limit: Int, offset: Int): [PostTagStats!]!
  # SysNode查询
  sysNodes(
    id: ID
    where: SysNodeWhereInput
    sort: [SysNodeSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): SysNodeResult!
  # SysNode统计
  sysNodeStats(where: SysNodeWhereInput, groupBy: [String!], having: SysNodeHavingInput, limit: Int, offset: Int): [SysNodeStats!]!
  # SysRole查询
  sysRoles(
    id: ID
    where: SysRoleWhereInput
    sort: [SysRoleSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): SysRoleResult!
  # SysRole统计
  sysRoleStats(where: SysRoleWhereInput, groupBy: [String!], having: SysRoleHavingInput, limit: Int, offset: Int): [SysRoleStats!]!
  # SysRule查询
  sysRules(
    id: ID
    where: SysRuleWhereInput
    sort: [SysRuleSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): SysRuleResult!
  # SysRule统计
  sysRuleStats(where: SysRuleWhereInput, groupBy: [String!], having: SysRuleHavingInput, limit: Int, offset: Int): [SysRuleStats!]!
  # SysTeam查询
  sysTeams(
    id: ID
    where: SysTeamWhereInput
    sort: [SysTeamSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): SysTeamResult!
  # SysTeam统计
  sysTeamStats(where: SysTeamWhereInput, groupBy: [String!], having: SysTeamHavingInput, limit: Int, offset: Int): [SysTeamStats!]!
  # SysUser查询
  sysUsers(
    id: ID
    where: SysUserWhereInput
    sort: [SysUserSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): SysUserResult!
  # SysUser统计
  sysUserStats(where: SysUserWhereInput, groupBy: [String!], having: SysUserHavingInput, limit: Int, offset: Int): [SysUserStats!]!
  # Tag查询
  tags(
    id: ID
    where: TagWhereInput
    sort: [TagSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): TagResult!
  # Tag统计
  tagStats(where: TagWhereInput, groupBy: [String!], having: TagHavingInput, limit: Int, offset: Int): [TagStats!]!
  # User查询
  users(
    search: String
    id: ID
    where: UserWhereInput
    sort: [UserSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): UserResult!
  # User统计
  userStats(where: UserWhereInput, groupBy: [String!], having: UserHavingInput, limit: Int, offset: Int): [UserStats!]!
}

# 订阅根类型
type Subscription {
  # AppHistory查询
  appHistories(
    id: ID
    where: AppHistoryWhereInput
    sort: [AppHistorySortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): AppHistoryResult!
  # AppLineage查询
  appLineages(
    id: ID
    where: AppLineageWhereInput
    sort: [AppLineageSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): AppLineageResult!
  # Comment查询
  comments(
    id: ID
    where: CommentWhereInput
    sort: [CommentSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): CommentResult!
  # OssFile查询
  ossFiles(
    id: ID
    where: OssFileWhereInput
    sort: [OssFileSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): OssFileResult!
  # OssHost查询
  ossHosts(
    id: ID
    where: OssHostWhereInput
    sort: [OssHostSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): OssHostResult!
  # Post查询
  posts(
    search: String
    id: ID
    where: PostWhereInput
    sort: [PostSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): PostResult!
  # PostTag查询
  postTags(
    id: ID
    where: PostTagWhereInput
    sort: [PostTagSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): PostTagResult!
  # SysNode查询
  sysNodes(
    id: ID
    where: SysNodeWhereInput
    sort: [SysNodeSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): SysNodeResult!
  # SysRole查询
  sysRoles(
    id: ID
    where: SysRoleWhereInput
    sort: [SysRoleSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): SysRoleResult!
  # SysRule查询
  sysRules(
    id: ID
    where: SysRuleWhereInput
    sort: [SysRuleSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): SysRuleResult!
  # SysTeam查询
  sysTeams(
    id: ID
    where: SysTeamWhereInput
    sort: [SysTeamSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): SysTeamResult!
  # SysUser查询
  sysUsers(
    id: ID
    where: SysUserWhereInput
    sort: [SysUserSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): SysUserResult!
  # Tag查询
  tags(
    id: ID
    where: TagWhereInput
    sort: [TagSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): TagResult!
  # User查询
  users(
    search: String
    id: ID
    where: UserWhereInput
    sort: [UserSortInput!]
    distinct: [String!]
    limit: Int
    offset: Int
    first: Int
    after: Cursor
    last: Int
    before: Cursor
  ): UserResult!
}

# 突变根类型
type Mutation {
  # AppHistory创建
  createAppHistory(input: AppHistoryCreateInput!): AppHistory!
  # AppHistory批量创建
  createAppHistories(input: [AppHistoryCreateInput!]!): [AppHistory!]!
  # AppHistory插入或更新（按on列冲突，缺省主键）
  upsertAppHistories(input: [AppHistoryCreateInput!]!, on: [String!]): [AppHistory!]!
  # AppHistory更新
  updateAppHistory(input: AppHistoryUpdateInput!, id: ID, where: AppHistoryWhereInput): AppHistory!
  # AppHistory删除
  deleteAppHistory(id: ID, where: AppHistoryWhereInput): Int!
  # AppLineage创建
  createAppLineage(input: AppLineageCreateInput!): AppLineage!
  # AppLineage批量创建
  createAppLineages(input: [AppLineageCreateInput!]!): [AppLineage!]!
  # AppLineage插入或更新（按on列冲突，缺省主键）
  upsertAppLineages(input: [AppLineageCreateInput!]!, on: [String!]): [AppLineage!]!
  # AppLineage更新
  updateAppLineage(input: AppLineageUpdateInput!, id: ID, where: AppLineageWhereInput): AppLineage!
  # AppLineage删除
  deleteAppLineage(id: ID, where: AppLineageWhereInput): Int!
  # Comment创建
  createComment(input: CommentCreateInput!): Comment!
  # Comment批量创建
  createComments(input: [CommentCreateInput!]!): [Comment!]!
  # Comment插入或更新（按on列冲突，缺省主键）
  upsertComments(input: [CommentCreateInput!]!, on: [String!]): [Comment!]!
  # Comment更新
  updateComment(input: CommentUpdateInput!, id: ID, where: CommentWhereInput): Comment!
  # Comment删除
  deleteComment(id: ID, where: CommentWhereInput): Int!
  # OssFile创建
  createOssFile(input: OssFileCreateInput!): OssFile!
  # OssFile批量创建
  createOssFiles(input: [OssFileCreateInput!]!): [OssFile!]!
  # OssFile插入或更新（按on列冲突，缺省主键）
  upsertOssFiles(input: [OssFileCreateInput!]!, on: [String!]): [OssFile!]!
  # OssFile更新
  updateOssFile(input: OssFileUpdateInput!, id: ID, where: OssFileWhereInput): OssFile!
  # OssFile删除
  deleteOssFile(id: ID, where: OssFileWhereInput): Int!
  # OssHost创建
  createOssHost(input: OssHostCreateInput!): OssHost!
  # OssHost批量创建
  createOssHosts(input: [OssHostCreateInput!]!): [OssHost!]!
  # OssHost插入或更新（按on列冲突，缺省主键）
  upsertOssHosts(input: [OssHostCreateInput!]!, on: [String!]): [OssHost!]!
  # OssHost更新
  updateOssHost(input: OssHostUpdateInput!, id: ID, where: OssHostWhereInput): OssHost!
  # OssHost删除
  deleteOssHost(id: ID, where: OssHostWhereInput): Int!
  # Post创建
  createPost(input: PostCreateInput!): Post!
  # Post批量创建
  createPosts(input: [PostCreateInput!]!): [Post!]!
  # Post插入或更新（按on列冲突，缺省主键）
  upsertPosts(input: [PostCreateInput!]!, on: [String!]): [Post!]!
  # Post更新
  updatePost(input: PostUpdateInput!, id: ID, where: PostWhereInput): Post!
  # Post删除
  deletePost(id: ID, where: PostWhereInput): Int!
  # PostTag删除
  deletePostTag(id: ID, where: PostTagWhereInput): Int!
  # SysNode创建
  createSysNode(input: SysNodeCreateInput!): SysNode!
  # SysNode批量创建
  createSysNodes(input: [SysNodeCreateInput!]!): [SysNode!]!
  # SysNode插入或更新（按on列冲突，缺省主键）
  upsertSysNodes(input: [SysNodeCreateInput!]!, on: [String!]): [SysNode!]!
  # SysNode更新
  updateSysNode(input: SysNodeUpdateInput!, id: ID, where: SysNodeWhereInput): SysNode!
  # SysNode删除
  deleteSysNode(id: ID, where: SysNodeWhereInput): Int!
  # SysRole创建
  createSysRole(input: SysRoleCreateInput!): SysRole!
  # SysRole批量创建
  createSysRoles(input: [SysRoleCreateInput!]!): [SysRole!]!
  # SysRole插入或更新（按on列冲突，缺省主键）
  upsertSysRoles(input: [SysRoleCreateInput!]!, on: [String!]): [SysRole!]!
  # SysRole更新
  updateSysRole(input: SysRoleUpdateInput!, id: ID, where: SysRoleWhereInput): SysRole!
  # SysRole删除
  deleteSysRole(id: ID, where: SysRoleWhereInput): Int!
  # SysRule创建
  createSysRule(input: SysRuleCreateInput!): SysRule!
  # SysRule批量创建
  createSysRules(input: [SysRuleCreateInput!]!): [SysRule!]!
  # SysRule插入或更新（按on列冲突，缺省主键）
  upsertSysRules(input: [SysRuleCreateInput!]!, on: [String!]): [SysRule!]!
  # SysRule更新
  updateSysRule(input: SysRuleUpdateInput!, id: ID, where: SysRuleWhereInput): SysRule!
  # SysRule删除
  deleteSysRule(id: ID, where: SysRuleWhereInput): Int!
  # SysTeam创建
  createSysTeam(input: SysTeamCreateInput!): SysTeam!
  # SysTeam批量创建
  createSysTeams(input: [SysTeamCreateInput!]!): [SysTeam!]!
  # SysTeam插入或更新（按on列冲突，缺省主键）
  upsertSysTeams(input: [SysTeamCreateInput!]!, on: [String!]): [SysTeam!]!
  # SysTeam更新
  updateSysTeam(input: SysTeamUpdateInput!, id: ID, where: SysTeamWhereInput): SysTeam!
  # SysTeam删除
  deleteSysTeam(id: ID, where: SysTeamWhereInput): Int!
  # SysUser创建
  createSysUser(input: SysUserCreateInput!): SysUser!
  # SysUser批量创建
  createSysUsers(input: [SysUserCreateInput!]!): [SysUser!]!
  # SysUser插入或更新（按on列冲突，缺省主键）
  upsertSysUsers(input: [SysUserCreateInput!]!, on: [String!]): [SysUser!]!
  # SysUser更新
  updateSysUser(input: SysUserUpdateInput!, id: ID, where: SysUserWhereInput): SysUser!
  # SysUser删除
  deleteSysUser(id: ID, where: SysUserWhereInput): Int!
  # Tag创建
  createTag(input: TagCreateInput!): Tag!
  # Tag批量创建
  createTags(input: [TagCreateInput!]!): [Tag!]!
  # Tag插入或更新（按on列冲突，缺省主键）
  upsertTags(input: [TagCreateInput!]!, on: [String!]): [Tag!]!
  # Tag更新
  updateTag(input: TagUpdateInput!, id: ID, where: TagWhereInput): Tag!
  # Tag删除
  deleteTag(id: ID, where: TagWhereInput): Int!
  # User创建
  createUser(input: UserCreateInput!): User!
  # User批量创建
  createUsers(input: [UserCreateInput!]!): [User!]!
  # User插入或更新（按on列冲突，缺省主键）
  upsertUsers(input: [UserCreateInput!]!, on: [String!]): [User!]!
  # User更新
  updateUser(input: UserUpdateInput!, id: ID, where: UserWhereInput): User!
  # User删除
  deleteUser(id: ID, where: UserWhereInput): Int!
}
